# Don't edit this file directly, as it will be overwritten by '../setup'.
#
# Typical usage:
# - make        # build parsers
# - make test   # parse
# - make clean
#
LANG = seq
include ../../lang/Makefile.common
