#! /usr/bin/env bash
#
# Generate makefiles needed to work for each test language comfortably.
#

for lang; do
  mkdir -p "$lang"
  test -e "$lang"/Makefile || ln -s ../Makefile.common "$lang"/Makefile
done
