#! /usr/bin/env bash
#
# Generate makefiles needed to work for each test language comfortably.
#

# shellcheck disable=SC2048
for lang in $* ; do
  (
    cd "$lang"
    cat > Makefile <<EOF
# Don't edit this file directly, as it will be overwritten by '../setup'.
#
# Typical usage:
# - make        # build parsers
# - make test   # parse
# - make clean
#
LANG = $lang
include ../../lang/Makefile.common
EOF
  )
done
