/* Auto-generated by codegen_type */
[@deriving show { with_path : false} ]
type token = string
and comment = token
and number = token
and variable = token
and intermediate1 = 
 | Intermediate_type1(assignment_statement)
 | Intermediate_type2(expression_statement)
and expression = 
 | Intermediate_type3(variable)
 | Intermediate_type4(number)
 | Intermediate_type5(intermediate4)
 | Intermediate_type6(intermediate5)
and intermediate5 = 
 | Intermediate_type7((expression, string /* * */, expression))
 | Intermediate_type8((expression, string /* / */, expression))
 | Intermediate_type9((expression, string /* ^ */, expression))
and intermediate4 = 
 | Intermediate_type10((expression, string /* + */, expression))
 | Intermediate_type11((expression, string /* - */, expression))
and expression_statement = (expression, string /* ; */)
and intermediate3 = (expression, string /* ; */)
and assignment_statement = (intermediate2, intermediate3)
and intermediate2 = (variable, string /* = */)
and program = list(intermediate1);
