/* Auto-generated by codegen_type */
type token = string
and identifier = token
and intermediate2 = option(c_rule)
and intermediate1 = list(b_rule)
and a_rule = string /* a */
and b_rule = string /* b */
and c_rule = string /* c */
and d_rule = string /* d */
and e_rule = string /* e */
and f_rule = string /* f */
and f_rule_alias = f_rule
and e_rule_alias = (e_rule)
and program = (a_rule, intermediate1, intermediate2, d_rule, e_rule_alias, f_rule_alias);
