#
# Generic makefile to be symlinked or to be included at the root of the
# semgrep-* folders as follows:
#
#   include ../common.mk
#

PROJECT_ROOT = $(shell git rev-parse --show-toplevel)
NAME = $(shell pwd | xargs basename)

# If grammar.js was present at a fixed location, we could define a simple
# make target like 'src/parser.c: grammar.js'.
.PHONY: build
build:
	$(MAKE) prep
	for dir in $$(find . -name grammar.js | xargs -I{} dirname {}); \
	do \
	  echo "Generate parser in $$(pwd)/$$dir"; \
	  if ! [ -e "$$dir/src/parser.c" ] \
	     || [ "$$dir/grammar.js" -nt "$$dir/src/parser.c" ]; then \
	    (cd "$$dir" && npx tree-sitter generate --no-bindings); \
	  else \
	    echo "$$dir/src/parser.c is up to date."; \
	  fi; \
	done

# Import, rename, patch etc. in a custom manner, as needed.
#
.PHONY: prep
prep:
	if [ -x prep ]; then ./prep; fi

.PHONY: test
test:
	for dir in $$(find . | grep 'grammar.js$$' | xargs -L1 dirname); do \
	  echo "Test $$dir"; \
	  (cd "$$dir" && npx tree-sitter test); \
	done

.PHONY: clean
clean:
	git clean -dfX
