--- ../../downloads/tree-sitter-0.22.6/Makefile	2024-05-05 13:47:18.000000000 -0700
+++ Makefile	2024-06-18 15:05:44.257992007 -0700
@@ -8,12 +8,12 @@

 # collect sources
 ifneq ($(AMALGAMATED),1)
-	SRC := $(wildcard lib/src/*.c)
-	# do not double-include amalgamation
-	SRC := $(filter-out lib/src/lib.c,$(SRC))
+  SRC := $(wildcard lib/src/*.c)
+  # do not double-include amalgamation
+  SRC := $(filter-out lib/src/lib.c,$(SRC))
 else
-	# use amalgamated build
-	SRC := lib/src/lib.c
+  # use amalgamated build
+  SRC := lib/src/lib.c
 endif
 OBJ := $(SRC:.c=.o)

@@ -28,21 +28,28 @@
 SONAME_MINOR := $(word 2,$(subst ., ,$(VERSION)))

 # OS-specific bits
+
+# This makefile doesn't work in a native Windows environment
 ifeq ($(OS),Windows_NT)
-	$(error "Windows is not supported")
-else ifeq ($(shell uname),Darwin)
-	SOEXT = dylib
-	SOEXTVER_MAJOR = $(SONAME_MAJOR).dylib
-	SOEXTVER = $(SONAME_MAJOR).$(SONAME_MINOR).dylib
-	LINKSHARED += -dynamiclib -Wl,-install_name,$(LIBDIR)/libtree-sitter.$(SONAME_MAJOR).dylib
+  # but it works with Cygwin
+  ifneq ($(OSTYPE),cygwin)
+    $(error "Windows is not supported by this Makefile")
+  endif
+endif
+
+ifeq ($(shell uname),Darwin)
+  SOEXT = dylib
+  SOEXTVER_MAJOR = $(SONAME_MAJOR).dylib
+  SOEXTVER = $(SONAME_MAJOR).$(SONAME_MINOR).dylib
+  LINKSHARED += -dynamiclib -Wl,-install_name,$(LIBDIR)/libtree-sitter.$(SONAME_MAJOR).dylib
 else
-	SOEXT = so
-	SOEXTVER_MAJOR = so.$(SONAME_MAJOR)
-	SOEXTVER = so.$(SONAME_MAJOR).$(SONAME_MINOR)
-	LINKSHARED += -shared -Wl,-soname,libtree-sitter.so.$(SONAME_MAJOR)
+  SOEXT = so
+  SOEXTVER_MAJOR = so.$(SONAME_MAJOR)
+  SOEXTVER = so.$(SONAME_MAJOR).$(SONAME_MINOR)
+  LINKSHARED += -shared -Wl,-soname,libtree-sitter.so.$(SONAME_MAJOR)
 endif
 ifneq ($(filter $(shell uname),FreeBSD NetBSD DragonFly),)
-	PCLIBDIR := $(PREFIX)/libdata/pkgconfig
+  PCLIBDIR := $(PREFIX)/libdata/pkgconfig
 endif

 all: libtree-sitter.a libtree-sitter.$(SOEXT) tree-sitter.pc
