#!/bin/bash
#
# Run tree-sitter's java parser on a sample program, emits a json AST.
#
set -eu

input_dir="."
output_dir="corpus"
input_files=$(find "$input_dir" -name '*.java')

count=0
errors=0

mkdir -p "$output_dir"

for file in $input_files; do
  count=$(( count + 1))
  node tree-sitter-parser.js "$file" > corpus/results"$count".json
  echo -n "$file: "
  if grep -qF "ERROR" corpus/results"$count".json \
      && ! grep -qF "ERROR" "$file"; then
    echo "ERROR"
    errors=$(( errors + 1 ))
  else
    echo "OK"
  fi
done

cat <<EOF
Input root: $input_dir
Output directory: $output_dir
Errors: $errors/$count
EOF
