/* Auto-generated by codegen_type */
type comment = string
and number = string
and variable = string
and intermediate1 = 
 | Intermediate_type1(assignment_statement)
 | Intermediate_type2(expression_statement)
and expression = 
 | Intermediate_type3(variable)
 | Intermediate_type4(number)
 | Intermediate_type5((expression, string, expression))
 | Intermediate_type6((expression, string, expression))
 | Intermediate_type7((expression, string, expression))
 | Intermediate_type8((expression, string, expression))
 | Intermediate_type9((expression, string, expression))
and expression_statement = (expression, string)
and assignment_statement = (variable, string, expression, string)
and program = list(intermediate1);
