#
# Generic makefile to build and test a parser for a specific language.
#

LANG = $(shell basename "$$(pwd)")
PROJECT_ROOT = $(shell git rev-parse --show-toplevel)
DUNE_BIN = $(PROJECT_ROOT)/bin
NODE_BIN = $(PROJECT_ROOT)/node_modules/.bin
SCRIPTS = $(PROJECT_ROOT)/scripts

ifndef GEN_OCAML_OPTIONS
  GEN_OCAML_OPTIONS =
endif

# Build the parsers.
#
.PHONY: build
build:
	$(MAKE) gen
	$(MAKE) build-ocaml

# Only generate source code without compiling it.
#
.PHONY: gen
gen:
	$(MAKE) gen-c
	$(MAKE) gen-ocaml

.PHONY: install
install:
	cd ocaml-src && dune install --root .

# Run the parsers on the collection of input programs in examples/
#
.PHONY: test
test:
	$(MAKE) parse-examples

.PHONY: gen-c
gen-c:
	$(SCRIPTS)/gen-c

.PHONY: gen-ocaml
gen-ocaml:
	$(SCRIPTS)/gen-ocaml --lang $(LANG) $(GEN_OCAML_OPTIONS)

.PHONY: build-ocaml
build-ocaml:
	$(SCRIPTS)/build-ocaml
	ln -sf ocaml-src/_build/install/default/bin/parse-$(LANG)

# Parse source using standalone executable and dump OCaml CST
.PHONY: parse-examples
parse-examples:
	$(SCRIPTS)/parse-examples $(LANG)

.PHONY: stat
stat:
	$(SCRIPTS)/lang-stat $(LANG) projects.txt extensions.txt

.PHONY: stat-priv
stat-priv:
	$(SCRIPTS)/lang-stat $(LANG) projects-priv.txt extensions.txt

.PHONY: clean
clean:
	rm -rf stat.tmp
	git clean -dfX
