#! /usr/bin/env bash
#
# Generate and build a tree-sitter parser from grammar.js and optionally
# src/scanner.c or src/scanner.cc
#
set -eu

project_root=$(git rev-parse --show-toplevel)

# Compile the C code into a parser that dumps the AST derived from its input.
#
npm init -y
npm install
