#! /usr/bin/env bash
#
# Check for various prerequisites and fail with helpful messages if they're
# missing.
#
set -eu

error() {
  cat 2>&1 <<EOF
Error: $*
EOF
  exit 1
}

echo "Check for bash arrays."
bash --version
things=() || error "Please upgrade bash. Bash version must be >= 4.4."
("${things[@]}") || error "Please upgrade bash. Bash version must be >= 4.4."

echo "Check for 'which'."
which which || error "Missing command: which"

echo "Check for 'opam'."
which opam || error "Missing command: opam"
echo "opam version: $(opam --version)"

echo "Check for 'node'."
which node || error "Missing command: node"
echo "node version: $(node --version)"

echo "Check for 'npm'."
which npm || error "Missing command: npm"
echo "npm version: $(npm --version)"
