#! /usr/bin/env bash
#
# Download the tree-sitter sources into downloads/tree-sitter
#
set -eu -o pipefail

prog_name=$(basename "$0")

error() {
  echo "Current directory: $(pwd)" >&2
  echo "Error: $@" >&2
  exit 1
}

usage() {
  cat <<EOF
Download the tree-sitter sources.
Usage: $prog_name [OPTIONS]
Options:
  --lazy
      Don't re-download the tree-sitter archive if its folder already
      exists locally for the specified version.
  --help
      Show this message and exit.
EOF
}

lazy=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --lazy)
      lazy=true
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      error "Invalid argument passed to '${prog_name}': '$1'"
  esac
  shift
done

./scripts/update-version-symlinks
version=$(cat tree-sitter-version)

mkdir -p downloads
(
  cd downloads

  echo "Downloading tree-sitter $version (lazy = $lazy)."
  src_dir=tree-sitter-"$version"
  if [[ "$lazy" = false && -d "$src_dir" ]]; then
    echo "Removing previous copy of tree-sitter."
    rm -rf "$src_dir"
  fi

  if [[ -d "$src_dir" ]]; then
    cat <<EOF
Re-using tree-sitter sources found locally:
  $(pwd)/$src_dir
EOF
  else
    echo "Fetching tarball for tree-sitter-$version."
    curl -LO https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v"$version".tar.gz
    tar xf v"$version".tar.gz
    if [[ ! -d "$src_dir" ]]; then
      error "Archive didn't unpack into the expected folder '$src_dir'."
    fi

    case "$version" in
      0.20.6)
      ;;
      0.22.6)
        # See https://github.com/tree-sitter/tree-sitter/pull/3417
        # regarding Windows/Cygwin support
        patch --backup \
          tree-sitter-0.22.6/Makefile \
          ../patch/tree-sitter-0.22.6/Makefile.patch
        ;;
      *)
        cat >&2 <<EOF
*** tree-sitter version: $version
*** Warning: tree-sitter 0.22.6 required patching the Makefile!
*** Remove this code once we're fully migrated to a version > 0.22.6
EOF
    esac
  fi
)
