#! /usr/bin/env bash
#
# Install the libtree-sitter runtime library.
# Must run from the ocaml-tree-sitter project root.
#
set -eu -o pipefail

error() {
  echo "Error: $@" >&2
  exit 1
}

echo "Installing tree-sitter library directly from git."
if [[ ! -e tree-sitter ]]; then
  git clone --depth 1 --branch 0.16.9 \
    https://github.com/tree-sitter/tree-sitter.git
fi
(
  cd tree-sitter
  git clean -dfX
  make
  sudo make install

  # Ensure libtree-sitter is found at linking time.
  # MacOS doesn't have ldconfig. Maybe it works without it?
  if which ldconfig > /dev/null; then
    libdir=$(
      pkg-config --libs-only-L tree-sitter \
      | sed -e 's/^-L//'
    )
    sudo ldconfig "$libdir"
  fi
)
