#! /usr/bin/env bash
#
# Steps for installing the tree-sitter tools used in the project.
#
set -eu

project_root=$(git rev-parse --show-toplevel)

# Install node modules at the project root.
# The tree-sitter executable will be in 'node_modules/.bin'.
(
  cd "$project_root"

  # tree-sitter-javascript is needed to generate grammar.json for typescript.
  #
  # tree-sitter-ruby is because I don't know how to compile the parser,
  # so our tests use the one from the npm package, whose grammar may
  # differ. FIXME
  #
  npm install \
    tree-sitter \
    tree-sitter-cli \
    tree-sitter-javascript \
    tree-sitter-ruby
)
