#! /usr/bin/env bash
#
# Steps for installing the tree-sitter tools used in the project.
#
set -eu

project_root=$(git rev-parse --show-toplevel)

# Install node modules at the project root.
# The tree-sitter executable will be in 'node_modules/.bin'.
(
  cd "$project_root"

  # tree-sitter-javascript is needed to generate grammar.json for typescript.
  npm install tree-sitter tree-sitter-cli tree-sitter-javascript
)
