#! /usr/bin/env bash
#
# Install the libtree-sitter runtime library.
# Must run from the ocaml-tree-sitter project root.
#

error() {
  echo "Error: $@" >&2
  exit 1
}

config=config.sh
[[ -f "$config" ]] || error "Missing config file. Did you run ./configure?"
. "$config"

(
  cd tree-sitter
  git pull origin master
  git clean -dfX
  make

  sudo make \
    PREFIX="$PREFIX" \
    INCLUDEDIR="$INCLUDEDIR" \
    LIBDIR="$LIBDIR" \
    install

  # MacOS doesn't have ldconfig. Maybe it works without it?
  if ldconfig --version > /dev/null; then
    sudo ldconfig "$LIBDIR"
  fi
)
