#! /usr/bin/env bash
#
# Install the tree-sitter CLI needed to generate parsers.
#
set -eu

if ! [[ -d tree-sitter ]]; then
  git clone https://github.com/tree-sitter/tree-sitter.git
fi

(
  cd tree-sitter
  cargo build
)

exe=$(pwd)/tree-sitter/target/debug/tree-sitter

if ! [[ -x "$exe" ]]; then
  cat >&2 <<EOF
Compilation of tree-sitter failed or the binary is not where we were
expecting it. The expected path is:
$exe
EOF
  exit 1
fi

cat <<EOF
The tree-sitter binary is:
$(pwd)/tree-sitter/target/debug/tree-sitter
EOF
