#! /usr/bin/env bash
#
# Install the tree-sitter C library and headers.
#
set -eu

if [[ ! -e tree-sitter ]]; then
  git clone --depth 1 https://github.com/tree-sitter/tree-sitter.git
fi

(
  cd tree-sitter
  git pull origin master
  git clean -dfX
  make
  sudo make install
  sudo ldconfig /usr/local/lib
)
