#! /usr/bin/env bash
#
# Install the tree-sitter CLI needed to generate parsers.
#
set -eu -o pipefail

prog_name=$(basename "$0")

# Installation root for the tree-sitter executable and runtime library
default_prefix=$(pwd)/tree-sitter

error() {
  echo "Current directory: $(pwd)" >&2
  echo "Error: $@" >&2
  exit 1
}

usage() {
  cat <<EOF
Compile the tree-sitter executable and install it.
Usage: $prog_name [OPTIONS]
Options:
  --help
      Show this message and exit.
  --prefix PATH
      Global installation directory for tree-sitter executables and libraries.
      Default: $default_prefix
EOF
}

prefix="$default_prefix"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --help)
      usage
      exit 0
      ;;
    --prefix)
      prefix="$2"
      shift
      ;;
    *)
      error "Invalid argument passed to '${prog_name}': '$1'"
  esac
  shift
done

bindir="$prefix"/bin

dir_name=$(dirname "$BASH_SOURCE")
"$dir_name"/download-tree-sitter --lazy

(
  cd downloads/tree-sitter
  # '--release' produces a smaller (3x) and faster (25x) executable
  cargo build --release
)

real_exe=downloads/tree-sitter/target/release/tree-sitter

if ! [[ -x "$real_exe" ]]; then
  cat >&2 <<EOF
Compilation of tree-sitter failed or the binary is not where we were
expecting it. The expected path is:
$real_exe
EOF
  exit 1
fi

mkdir -p "$bindir"
exe="$bindir/tree-sitter"
cp "$real_exe" "$exe"

cat <<EOF
The path to the tree-sitter command-line executable is:
  $exe
EOF
