#! /usr/bin/env bash
#
# Run OCaml parsers on the json output of tree-sitter in examples/
#
set -eu -o pipefail

usage() {
  cat <<EOF
Usage: $(basename "$0") LANG
Parse sample source files written in language LANG.
EOF
}

if [[ $# != 1 ]]; then
  usage >&2
  exit 1
fi

lang="$1"

parser=./parse-"$lang"

# Run the parser from source to ocaml CST
#
if [[ -d examples ]]; then
  for src in $(ls examples/*.src || :); do
    ast=${src%.src}.ast
    "$parser" "$src" 2>&1 | tee "$ast"
  done
fi
