#! /usr/bin/env bash
#
# Thorough cleanup and rebuild for development purposes.
#
# See 'Dockerfile' or '.circleci/config.yml' for similar steps that are
# continuously tested.
#
set -eu

if [[  ! -d .git \
   || -n "$(git rev-parse --show-superproject-working-tree)" ]]; then
  cat >&2 <<EOF
This script was only tested to work from the root of the ocaml-tree-sitter
repository, and not as a submodule as another repo.
EOF
  exit 1
fi

git submodule update --init --recursive --depth 1
git clean -dfX

if ! npm --version > /dev/null; then
  cat >&2 <<EOF
npm not found.
Try the following:

  ./scripts/setup-node

(needs root access to install system packages)
EOF
  exit 1
fi

# needs root access to install the tree-sitter library on non-brew systems
./scripts/install-tree-sitter-lib

./configure
eval $(opam env)
make setup
make
make install
make test
