#! /usr/bin/env bash
#
# Install Node.js so that we can install the tree-sitter command-line
# interface.
#

cat > ~/.npmrc <<EOF
prefix = ~/.node
EOF

cat >> ~/.bashrc <<"EOF"
export PATH="$HOME/.node/bin:$PATH"
export NODE_PATH="$HOME/.node/lib/node_modules:$NODE_PATH"
export MANPATH="$HOME/.node/share/man:$MANPATH"
EOF

if which apt-get > /dev/null 2>&1; then
  sudo apt-get update
  sudo apt-get install -y nodejs npm
elif which apk > /dev/null 2>&1; then
  sudo apk update
  sudo apk add nodejs npm
else
  echo "$0: Unknown or unsupported package manager." >&2
  exit 1
fi

npm install npm -g
