#! /usr/bin/env bash
#
# Slim down tree-sitter-* git repos by removing the most bulky generated
# code from the history.
#
set -eu -o pipefail

src_projects=(
  tree-sitter-javascript
)

src_org=tree-sitter
dst_org=returntocorp

rewrite_history() {
  files_to_remove="src/parser.c"
  # Not sure about all the details in what follows. It was copied from
  # https://itextpdf.com/en/blog/technical-notes/how-completely-remove-file-git-repository
  git filter-branch -f \
      --prune-empty \
      --tag-name-filter cat \
      --tree-filter 'find . -name parser.c | xargs rm -f' \
      -- --all
  git for-each-ref --format="%(refname)" refs/original/ \
    | xargs -n 1 git update-ref -d
  git reflog expire --expire=now --all && git gc --prune=now --aggressive
}

for src_project in "${src_projects[@]}"; do
  mkdir -p tmp
  (
    cd tmp
    rm -rf "$src_project"
    dst_project="$src_project"-slim
    src_remote=https://github.com/"$src_org"/"$src_project".git
    dst_remote=git@github.com:"$dst_org"/"$dst_project".git

    cat <<EOF
Slim down $src_remote
  -> $dst_remote
EOF
    git clone "$src_remote"
    (
      cd "$src_project"
      rewrite_history
      git remote add slim "$dst_remote"
      git push -f slim master
    )
  )
done
