#! /usr/bin/env bash
#
# Parse examples into examples/*.json with tree-sitter-ruby
#

if [[ -d examples ]]; then
  for input in $(ls examples/*.src || :); do
    output=${input%.src}.json
    ./tree-sitter-ruby.js "$input" | ydump > "$output"
  done
fi
