#
# Generic makefile to symlinked or to be included at the root of the
# semgrep-* folders as follows:
#
#   include ../common.mk
#

PROJECT_ROOT = $(shell git rev-parse --show-toplevel)
TREE_SITTER = $(PROJECT_ROOT)/node_modules/.bin/tree-sitter
NAME = $(shell pwd | xargs basename)

.PHONY: build
build:
	$(MAKE) prep
	for dir in $$(find . | grep 'grammar.js$$' | xargs dirname); do \
	  echo "Generate parser in $$dir"; \
	  (cd "$$dir" && $(TREE_SITTER) generate); \
	done

# Import, rename, patch etc. in a custom manner, as needed.
#
.PHONY: prep
prep:
	if [ -x prep ]; then ./prep; fi

.PHONY: test
test:
	for dir in $$(find . | grep 'grammar.js$$' | xargs dirname); do \
	  echo "Test $$dir"; \
	  (cd "$$dir" && $(TREE_SITTER) test); \
	done

.PHONY: clean
clean:
	git clean -dfX
