#! /usr/bin/env bash
#
# Gather the javascript files to form a usable grammar.js for parsing
# typescript.
#
set -eu

project_root=$(git rev-parse --show-toplevel)
scripts="$project_root"/scripts

# Without a suffix added after removing leading underscores, tree-sitter
# code generation enters an infinite loop.
#
# This is an issue at least for 'jsx_element' and '_jsx_element'. We can't
# just remove the leading underscore from the latter.
#
#
suffix="_x"

"$scripts"/simplify-grammar --suffix "$suffix" < orig/define-grammar.js \
  > define-grammar.js

# This occurs in a conditional.
# Look for things like "if (dialect === 'typescript')"
#
sed -i -e "s/'_jsx_element'/'jsx_element$suffix'/g" define-grammar.js

"$scripts"/simplify-grammar --suffix "$suffix" < orig/javascript-grammar.js \
  > javascript-grammar.js

cp orig/grammar.js .
