#! /usr/bin/env bash
#
# Gather the javascript files to form a usable grammar.js for parsing
# typescript.
#
set -eu

project_root=$(git rev-parse --show-toplevel)
scripts="$project_root"/scripts

cp orig/define-grammar.js define-grammar.js
cp orig/javascript-grammar.js javascript-grammar.js
cp orig/grammar.js .
