name: pre-commit

on:
  push:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - uses: semgrep/setup-ocaml@ce6a88f72f48e02a172c93eb93177b21659e7032
        with:
          cache-prefix: v5
          ocaml-compiler: ocaml-variants.5.3.0+options,ocaml-option-flambda
          opam-pin: false
          save-opam-post-run: true

      - name: Install ocp-indent and add to PATH
        run: |
          opam install -y ocp-indent
          echo "$(opam var bin)" >> "$GITHUB_PATH"

      - name: Set up uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
          cache-dependency-glob: .pre-commit-config.yaml
          version: "0.11.x"
      - name: Cache pre-commit hook envs
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-v1|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install and run pre-commit
        run: |
          UV_EXCLUDE_NEWER="1 week" uv tool install pre-commit --with pre-commit-uv
          pre-commit run --show-diff-on-failure --color=always --all-files
